mod 3.1.07

diff --git a/package/my/luci-app-clash/root/etc/init.d/clash b/package/my/luci-app-clash/root/etc/init.d/clash
--- a/package/my/luci-app-clash/root/etc/init.d/clash
+++ b/package/my/luci-app-clash/root/etc/init.d/clash
@@ -1,154 +1,436 @@
 #!/bin/sh /etc/rc.common
-# Copyright (C) 2009-2010 OpenWrt.org
+# Copyright (c) 2011-2015 OpenWrt.org
 
 START=99
 STOP=15
 
-CLASH="/usr/bin/clash"
+
+CLASH="/etc/clash/clash"
 CLASH_CONFIG="/etc/clash"
+CRON_FILE="/etc/crontabs/root"
 
-add_rule() {
-	server_port=$(uci get clash.config.server_port 2>/dev/null)
-	server=$(uci get clash.config.server 2>/dev/null)
-	proxy_port=$(uci get clash.config.proxy_port 2>/dev/null)
-	socks5_port=$(uci get clash.config.socks5_port 2>/dev/null)
+USE_PROCD=1
 
-	# 设置 iptables
-	iptables -t nat -N CLASH
+PDNSD_BIN="/var/sbin/dnscache"
 
-	# 8080 是 ss 代理服务器的端口，即远程 CLASH 服务器提供服务的端口，如果你有多个 ip 可用,但端口一致，就设置这个
-	if [ $server_port -ne 0 ]; then
-		iptables -t nat -A CLASH -p tcp --dport $server_port -j RETURN
+pdnsd_genconfig() {
+
+  DNS_SERVER=$(uci get clash.config.dnsserver 2>/dev/null)
+  dnsserver_d=$(uci get clash.config.dnsserver_d 2>/dev/null)
+  pdnsd_port=$(uci get clash.config.dns_server |awk -F '#' '{print $2}' 2>/dev/null)
+  dnscachee=$(uci get clash.config.dns_server_d |awk -F '#' '{print $2}' 2>/dev/null)
+	[ -d /var/etc ] || mkdir -p /var/etc
+
+  if [ ! -f /var/dnscache/pdnsd.cache ]; then
+    mkdir -p /var/dnscache
+    echo -ne "pd13\000\000\000\000" > /var/dnscache/pdnsd.cache
+    chown -R nobody.nogroup /var/dnscache
 	fi
-
-	# 192.192.192.192 是 CLASH 代理服务器的 ip, 如果你只有一个 CLASH服务器的 ip，却能选择不同端口,就设置此条
-	if [ $server -ne 0 ]; then
-		iptables -t nat -A CLASH -d $server -j RETURN
-	fi
-
-	if [ $socks5_port -ne 0 ]; then
-		iptables -t nat -A CLASH -p tcp \
-			-j REDIRECT --to-ports $socks5_port 2>/dev/null || {
-			loger 3 "Can't redirect, please check the iptables."
-			exit 1
-		}
-	fi
-
-	# 保留地址、私有地址、回环地址 不走代理
-	iptables -t nat -A CLASH -d 0.0.0.0/8 -j RETURN
-	iptables -t nat -A CLASH -d 10.0.0.0/8 -j RETURN
-	iptables -t nat -A CLASH -d 127.0.0.0/8 -j RETURN
-	iptables -t nat -A CLASH -d 169.254.0.0/16 -j RETURN
-	iptables -t nat -A CLASH -d 172.16.0.0/12 -j RETURN
-	iptables -t nat -A CLASH -d 192.168.0.0/16 -j RETURN
-	iptables -t nat -A CLASH -d 224.0.0.0/4 -j RETURN
-	iptables -t nat -A CLASH -d 240.0.0.0/4 -j RETURN
-
-	# 7892是clash_redir端口
-	iptables -t nat -A CLASH -p tcp -j REDIRECT --to-ports $proxy_port
-
-	iptables -t nat -A PREROUTING -p tcp -j CLASH
-
+	
+	cat > /var/etc/dnscache.conf <<EOF
+global {
+    perm_cache=1024;        
+    cache_dir="/var/dnscache";     
+    pid_file = /var/run/dnscache.pid;
+    server_ip = 0.0.0.0;        
+    server_port=$dnscachee;           
+    status_ctl = on;
+    paranoid=on;                  
+    query_method=udp_only;      
+    neg_domain_pol = off;  
+    par_queries = 400;          
+    min_ttl = 1h;               
+    max_ttl = 1w;               
+    timeout = 10;               
 }
 
-del_rule() {
-	# 清除 iptables
-	srulecount=`iptables -L|grep CLASH|wc -l`
-	if [ $srulecount -gt 0 ] ;then
-		iptables -t nat -F CLASH
-		iptables -t nat -D PREROUTING -p tcp -j CLASH
-		iptables -t nat -X CLASH
-	fi
-}	
+server {  
+    label = "routine";         
+    ip = $DNS_SERVER;     
+    timeout = 20;              
+    reject = 74.125.127.102,  
+        74.125.155.102,  
+        74.125.39.102,  
+        74.125.39.113,  
+        209.85.229.138,  
+        128.121.126.139,  
+        159.106.121.75,  
+        169.132.13.103,  
+        192.67.198.6,  
+        202.106.1.2,  
+        202.181.7.85,  
+        203.161.230.171,  
+        203.98.7.65,  
+        207.12.88.98,  
+        208.56.31.43,  
+        209.145.54.50,  
+        209.220.30.174,  
+        209.36.73.33,  
+        211.94.66.147,  
+        213.169.251.35,  
+        216.221.188.182,  
+        216.234.179.13,  
+        243.185.187.39,  
+        37.61.54.158,  
+        4.36.66.178,  
+        46.82.174.68,  
+        59.24.3.173,  
+        64.33.88.161,  
+        64.33.99.47,  
+        64.66.163.251,  
+        65.104.202.252,  
+        65.160.219.113,  
+        66.45.252.237,  
+        69.55.52.253,  
+        72.14.205.104,  
+        72.14.205.99,  
+        78.16.49.15,  
+        8.7.198.45,  
+        93.46.8.89,  
+        37.61.54.158,  
+        243.185.187.39,  
+        190.93.247.4,  
+        190.93.246.4,  
+        190.93.245.4,  
+        190.93.244.4,  
+        65.49.2.178,  
+        189.163.17.5,  
+        23.89.5.60,  
+        49.2.123.56,  
+        54.76.135.1,  
+        77.4.7.92,  
+        118.5.49.6,  
+        159.24.3.173,  
+        188.5.4.96,  
+        197.4.4.12,  
+        220.250.64.24,  
+        243.185.187.30,  
+        249.129.46.48,  
+        253.157.14.165;  
+    reject_policy = fail;  
+}
 
-change_dns() {
-	local dns_server=$(uci get clash.config.dns_server 2>/dev/null)
-	#修改dnsmasq
-	uci delete dhcp.@dnsmasq[0].server
+server {  
+    label = "special";                  
+    ip = $dnsserver_d; 
+    port = $pdnsd_port;                        
+    proxy_only = on;
+    timeout = 20;	
+}
+
+
+  
+
+source {
+	owner=localhost;
+//	serve_aliases=on;
+	file="/etc/hosts";
+}
+
+rr {
+	name=localhost;
+	reverse=on;
+	a=127.0.0.1;
+	owner=localhost;
+	soa=localhost,root.localhost,42,86400,900,86400,86400;
+}
+EOF
+  
+  [ -d /var/sbin ] || mkdir -p /var/sbin
+  [ -f /var/sbin/dnscache ] || cp -a /usr/sbin/pdnsd /var/sbin/dnscache
+}
+
+
+
+start_pdnsd() {
+  pdnsd_port=$(uci get clash.config.dns_server |awk -F '#' '{print $2}' 2>/dev/null)
+  dnsserver_d=$(uci get clash.config.dnsserver_d 2>/dev/null)
+	local usr_dns="$1"
+    local usr_port="$2"
+  
+	
+	[ -z "$usr_dns" ] && usr_dns="8.8.8.8"
+	[ -z "$usr_port" ] && usr_port="53"
+
+  [ -d /var/etc ] || mkdir -p /var/etc
+
+   if [ ! -d /var/pdnsd ];then
+       mkdir -p /var/pdnsd
+       echo -ne "pd13\000\000\000\000" >/var/pdnsd/pdnsd.cache
+       chown -R nobody:nogroup /var/pdnsd
+   fi
+	
+	cat > /var/etc/pdnsd.conf <<EOF
+global {
+	perm_cache=1024;
+	cache_dir="/var/pdnsd";
+	pid_file = /var/run/pdnsd.pid;
+	run_as="nobody";
+	server_ip = 0.0.0.0;
+	server_port = $pdnsd_port;
+	status_ctl = on;
+	query_method = tcp_only;
+	min_ttl=1h;
+	max_ttl=1w;
+	timeout=20;
+	neg_domain_pol=on;
+	proc_limit=2;
+	procq_limit=8;
+}
+
+
+server {
+	label= "v2-usrdns";
+	ip = $usr_dns;
+	port = $usr_port;
+	timeout=20;
+	uptest=none;
+	interval=10m;
+	purge_cache=off;
+}
+server {
+	label= "v2-pdnsd";
+	ip = $dnsserver_d;
+	port = $pdnsd_port;
+	timeout=20;
+	uptest=none;
+	interval=10m;
+	purge_cache=off;
+}
+EOF
+
+	/usr/sbin/pdnsd -c /var/etc/pdnsd.conf -d
+	
+}
+
+
+change_dns(){
+dns_server=$(uci get clash.config.dns_server 2>/dev/null)
+dns_serve1=$(uci get dhcp.@dnsmasq[0].server 2>/dev/null)
+dns_server_d=$(uci get clash.config.dns_server_d 2>/dev/null)
+	if [ $dns_serve1 ]; then
+		uci del dhcp.@dnsmasq[-1].server
+	fi	
+	uci add_list dhcp.@dnsmasq[0].server=$dns_server_d
 	uci add_list dhcp.@dnsmasq[0].server=$dns_server
 	uci delete dhcp.@dnsmasq[0].resolvfile
 	uci set dhcp.@dnsmasq[0].noresolv=1
 	uci commit dhcp
-
 }
 
 revert_dns() {
-	local dns_server=$(uci get clash.config.dns_server 2>/dev/null)
-	local dns_serve1=$(uci get dhcp.@dnsmasq[0].server 2>/dev/null)
-	#还原dnsmasq修改
-	if [ $dns_serve1 = $dns_server ]; then
-		uci delete dhcp.@dnsmasq[0].server
-		uci delete dhcp.@dnsmasq[0].resolvfile
-		uci delete dhcp.@dnsmasq[0].noresolv
-		uci commit dhcp
+	uci del dhcp.@dnsmasq[-1].server
+	uci set dhcp.@dnsmasq[0].resolvfile=/tmp/resolv.conf.auto
+	uci set dhcp.@dnsmasq[0].noresolv=0
+	uci commit dhcp
+}
+
+add_cron(){
+	sed -i '/clash.log/d' $CRON_FILE
+	echo '0 0 * * 0 echo "" > /tmp/clash.log' >> $CRON_FILE
+	[ -n "$(grep -w "/usr/share/clash/clash.sh" $CRON_FILE)" ] && sed -i '/\/usr\/share\/clash\/clash.sh/d' $CRON_FILE
+	[ $(uci get clash.config.auto_update 0) -eq 1 ] && echo "0 $(uci get clash.config.auto_update_time) * * * /usr/share/clash/clash.sh" >> $CRON_FILE
+	crontab $CRON_FILE
+}
+
+del_cron()
+{
+	sed -i '/clash/d' $CRON_FILE
+	sed -i '/clash.log/d' $CRON_FILE
+	/etc/init.d/cron restart
+}
+
+
+get_dnsmasq() {
+	local pid=$(pidof dnsmasq)
+	[ $? -ne 0 ] && echo "/tmp/dnsmasq.d"
+	local conf_dir=$(cat /etc/dnsmasq.conf | grep conf-dir= | sed 's/.*=//')
+	local conf_tmp=$(cat /proc/$pid/cmdline | grep dnsmasq.conf)
+	local conf_dir_tmp=$(cat $conf_tmp | grep conf-dir= | sed 's/.*=//')
+	if [ -n "$conf_dir" ]; then
+		echo $conf_dir
+	elif [  -n "$conf_dir_tmp" ];then
+		echo $conf_dir_tmp
+	else
+		echo "/tmp/dnsmasq.d"
 	fi
 }
 
-start() {
-	local enable=$(uci get clash.config.enabled 2>/dev/null)
-	local dns1=$(uci get flowoffload.@flow[0].dns 2>/dev/null)
-	local dns2=$(uci get sfe.config.dns 2>/dev/null)
-	# 启动 Clash
-	if [ $enable -eq 1 ]; then
-		kill -9 $(ps | grep clash-watchdog.sh | grep -v "grep" | awk '{print $1}') >/dev/null 2>&1
-		if [ $dns1 -eq 1 ];  then
-			uci set flowoffload.@flow[0].dns=0
-			uci commit flowoffload
-			/etc/init.d/flowoffload restart > /dev/null 2>&1
-			sleep 2
-		fi
-		if [ $dns2 -eq 1 ];  then
-			uci set sfe.@config[0].dns=0
-			uci commit sfe
-			/etc/init.d/sfe restart > /dev/null 2>&1
-			sleep 2
-		fi
-		del_rule
-		revert_dns
 
-		if pidof clash >/dev/null; then
-			kill $(pidof clash) >/dev/null 2>&1 || kill -9 clash >/dev/null 2>&1
-			sleep 2
-		fi
+dns_poisoning() {
+	local gfw_list=/etc/clash/dnsmasq_gfwlist.conf
+	local gfw_list_tmp=$dnsmasq_confdir/dnsmasq_gfwlist.conf
+	start_pdnsd
+			
+	[ ! -f $gfw_list_tmp ] && {
+		ln -s $gfw_list $gfw_list_tmp
+	}	
+}
 
-		echo "enable"
-		nohup $CLASH -d $CLASH_CONFIG > /tmp/clash.log 2>&1 &
-
-		if pidof clash >/dev/null; then
-			sleep 3
-			echo "clash以启动,加载规则"
-			add_rule
-			change_dns
-			/etc/init.d/dnsmasq restart > /dev/null 2>&1
-			#if [ usr/bin/clash ] ;then
-				#[ -z "$(grep -w "/usr/share/clash/clash_update.sh" /etc/crontabs/root)" ] && echo "0 4 * * * /usr/share/clash/clash_update.sh" >> /etc/crontabs/root
-				#crontab /etc/crontabs/root
-			#fi
-			nohup /usr/share/clash/clash-watchdog.sh > /var/log/clash-watchdog.file 2>&1 &
-		else
-			echo "clash无法启动"
-		fi
+yml_change(){
+	proxy_port=$(uci get clash.config.proxy_port 2>/dev/null)
+	redir_port=`grep redir-port: /etc/clash/config.yml |awk -F ' ' '{print $2}'`
+	if [ -z $redir_port ]; then
+	   sed -i "2i\redir-port: ${proxy_port}" /etc/clash/config.yml
+	else
+	      sed -i '/redir-port:/ d' /etc/clash/config.yml
+	      sed -i "2i\redir-port: ${proxy_port}" /etc/clash/config.yml
+	fi
+	
+	grep dns: /etc/clash/config.yml
+	if [ "$?" -ne "0" ]; then
+   	 sed -i "/Proxy:/i\dns:" /etc/clash/config.yml
+   	 sed -i "/dns:/a\  enable: true" /etc/clash/config.yml
+         sed -i "/enable: true/a\  ipv6: false" /etc/clash/config.yml
+         sed -i "/ipv6: false/a\  listen: 0.0.0.0:7874" /etc/clash/config.yml
+         sed -i "/listen: 0.0.0.0:7874/a\  enhanced-mode: redir-host" /etc/clash/config.yml
+         sed -i "/enhanced-mode: redir-host/a\  nameserver:" /etc/clash/config.yml
+         sed -i "/nameserver:/a\  - 114.114.114.114" /etc/clash/config.yml
+         sed -i "/114.114.114.114/a\  - 119.29.29.29" /etc/clash/config.yml
+         sed -i "/119.29.29.29/a\  - 223.5.5.5" /etc/clash/config.yml
+         sed -i "/223.5.5.5/a\  fallback:" /etc/clash/config.yml
+         sed -i "/fallback:/a\  - tls://dns.rubyfish.cn:853" /etc/clash/config.yml
+         sed -i "/dns.rubyfish.cn:853/a\  - tls://1.1.1.1:853" /etc/clash/config.yml
+         sed -i "/1.1.1.1:853/a\  - tcp://208.67.222.222:443" /etc/clash/config.yml
+         sed -i "/208.67.222.222:443/a\  - tls://dns.google" /etc/clash/config.yml
+        fi
+	allow_lan=`grep allow-lan: /etc/clash/config.yml |awk -F ' ' '{print $2}'`
+	allow_lan_r=$(echo $allow_lan |tr   [a-z]   [A-Z]) 
+	if [ $allow_lan_r == "FALSE" ]; then
+	   sed -i '/allow-lan:/ d' /etc/clash/config.yml
+	   sed -i "4i\allow-lan: true" /etc/clash/config.yml
 	fi
 }
 
-stop() {
-	kill -9 $(ps | grep clash-watchdog.sh | grep -v "grep" | awk '{print $1}') >/dev/null 2>&1
+
+yml_dns_change(){
+    dns=$(uci get clash.config.dns 2>/dev/null)
+	if [ $dns -ne 1 ];  then
+	   dns_port=`grep listen: /etc/clash/config.yml |awk -F ':' '{print $3}' |tr -cd "[0-9]"`
+	   if [ $dns_port -eq 53 ]; then
+	      sed -i '/listen:/ d' /etc/clash/config.yml
+	      sed -i "/nameserver:/i\  listen: 0.0.0.0:7874" /etc/clash/config.yml
+	      uci del dhcp.@dnsmasq[-1].server
+	      uci add_list dhcp.@dnsmasq[0].server=127.0.0.1#7874
+	      uci delete dhcp.@dnsmasq[0].resolvfile
+	      uci set dhcp.@dnsmasq[0].noresolv=1
+	      uci commit dhcp
+	    else
+	      uci del dhcp.@dnsmasq[-1].server
+	      uci add_list dhcp.@dnsmasq[0].server=127.0.0.1#$dns_port
+	      uci delete dhcp.@dnsmasq[0].resolvfile
+	      uci set dhcp.@dnsmasq[0].noresolv=1
+	      uci commit dhcp
+	   fi
+    fi
+}
+
+
+start_service(){
+
+proxy_port=$(uci get clash.config.proxy_port 2>/dev/null)
+
+enable=$(uci get clash.config.enable 2>/dev/null)
+
+if [ $enable -eq 1 ]; then
+    yml_change
+    yml_dns_change
+   
+	nohup $CLASH -d "$CLASH_CONFIG" > /tmp/clash.log 2>&1 &
+	
+    ln -s /usr/share/clash/web /www/clash
+		 
+	dns=$(uci get clash.config.dns 2>/dev/null)
+	bbr=$(uci get clash.config.bbr 2>/dev/null)
+	  
+	if [ $dns -eq 1 ];  then
+		pdnsd_genconfig		
+		procd_open_instance
+		procd_set_param command "$PDNSD_BIN" -c /var/etc/dnscache.conf
+		procd_set_param respawn
+		procd_set_param stderr 1
+		procd_close_instance
+		change_dns
+                dnsmasq_confdir=$(get_dnsmasq)
+	        dns_poisoning
+	fi
+	  
+	if [ $bbr -eq 1 ];  then
+		sysctl -w net.ipv4.tcp_congestion_control=bbr
+	else
+		sysctl -w net.ipv4.tcp_congestion_control=cubic
+	fi
+	uci set firewall.@defaults[0].flow_offloading=1
+        uci commit firewall
+	/etc/init.d/firewall restart >/dev/null 2>&1
+	
+	
+    iptables -t nat -N clash
+                
+    iptables -t nat -A clash -d 0.0.0.0/8 -j RETURN
+    iptables -t nat -A clash -d 10.0.0.0/8 -j RETURN
+    iptables -t nat -A clash -d 127.0.0.0/8 -j RETURN
+    iptables -t nat -A clash -d 169.254.0.0/16 -j RETURN
+    iptables -t nat -A clash -d 172.16.0.0/12 -j RETURN
+    iptables -t nat -A clash -d 192.168.0.0/16 -j RETURN
+    iptables -t nat -A clash -d 224.0.0.0/4 -j RETURN
+    iptables -t nat -A clash -d 240.0.0.0/4 -j RETURN
+         
+    iptables -t nat -A clash -p tcp -j REDIRECT --to-ports $proxy_port
+        
+    iptables -t nat -A PREROUTING -p tcp -j clash
+	
+	/etc/init.d/dnsmasq restart >/dev/null 2>&1
+	
+	
 	if pidof clash >/dev/null; then
-		# 关闭 Clash
-		kill $(pidof clash) >/dev/null 2>&1 || kill -9 clash >/dev/null 2>&1
-		del_rule
-		revert_dns
-		/etc/init.d/dnsmasq restart > /dev/null 2>&1
-		sed -i '/clash_update/d' /etc/crontabs/root
-		/etc/init.d/cron restart > /dev/null 2>&1
-		echo "stop!"
+		add_cron
+	else
+		echo "CANNOT START"
+	fi
+	
+fi
+}
+
+
+
+stop_service(){
+
+	srulecount=`iptables -L|grep clash|wc -l`
+	if [ $srulecount -gt 0 ] ;then
+		iptables -t nat -F clash
+		iptables -t nat -D PREROUTING -p tcp -j clash
+		iptables -t nat -X clash
 	fi
 
+	kill -9 $(ps | grep pdnsd | grep -v grep | awk '{print $1}') >/dev/null 2>&1 
+
+	kill -9 `pidof clash|sed "s/$//g"` 2>/dev/null
+	
+	sysctl -w net.ipv4.tcp_congestion_control=cubic
+    
+	kill $(pidof dnscache) >/dev/null 2>&1 || kill -9 $(ps | grep dnscache | grep -v grep | awk '{print $1}') >/dev/null 2>&1
+	
+	revert_dns
+	uci set firewall.@defaults[0].flow_offloading=1
+    uci commit firewall
+	
+	/etc/init.d/firewall restart >/dev/null 2>&1
+	
+    /etc/init.d/dnsmasq restart >/dev/null 2>&1
+
+     	dnsmasq_confdir=$(get_dnsmasq)
+	rm -rf $dnsmasq_confdir/dnsmasq_gfwlist.conf
+
+    rm -rf /www/clash 2> /dev/null
+    del_cron
 }
+
 
 restart(){
-	stop
-	sleep 2
-	start
-	echo "restarted."
+    stop
+    start
 }
+
+
+
